config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :events, :only => [:index, :new, :create, :show]
  resources :tickets

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  # Built in validators
  validates :artist, :presence => true, :length => { minimum: 3 }
  validates :price_low, :presence => true, :numericality => true
  validates :price_high, :presence => true, :numericality => true
  validates :event_date, :presence => true

  # Custom validators
  validate :price_high_value, :event_not_passed

  # Relations
  has_many :tickets

  def event_not_passed
    if event_date.presence && event_date < Date.today
      errors.add('Event', 'already passed')
    end
  end

  def price_high_value
    if price_high.presence && price_low.presence && price_high < price_low
      errors.add('Price high', "value should be equal to #{price_low} or larger")
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  # Built in validators
  validates :name, :presence => true, :length => { minimum: 2 }
  validates :address, :presence => true, :length => { minimum: 6 }
  validates :price, :presence => true, :numericality => true
  validates :email_address, :presence => true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, :presence => true, :length => { minimum: 9, maximum: 13 }

  # Relations
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Relations
  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :is_logged_in, :only => [:new, :create]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date)
    end

    def is_logged_in
      authenticate_or_request_with_http_basic("Ads") do |username, password|
        username == "admin" && password == "admin"
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = current_user.id

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id)
    end

    def correct_user
      @user_ticket = current_user.tickets.find_by(id: params[:id])
      redirect_to tickets_path, notice: "You're not allowed to edit this ticket" if @user_ticket.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation" class="mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title">
        <h6 style="margin: 0"><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h6>
      </div>

      <div class="mdl-card__supporting-text">
        <ul style="margin-top: 0;">
          <% event.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="mdl-textfield mdl-js-textfield" style="display: flex;">
    <%= form.label :artist, class: 'mdl-textfield__label' %>
    <%= form.text_field :artist, class: 'mdl-textfield__input' %>
  </div>

  <div class="mdl-textfield mdl-js-textfield" style="display: flex;">
    <%= form.label :description, class: 'mdl-textfield__label' %>
    <%= form.text_area :description, class: 'mdl-textfield__input' %>
  </div>

  <div class="mdl-textfield mdl-js-textfield" style="display: flex;">
    <%= form.label :price_low, class: 'mdl-textfield__label' %>
    <%= form.text_field :price_low, class: 'mdl-textfield__input' %>
  </div>

  <div class="mdl-textfield mdl-js-textfield" style="display: flex;">
    <%= form.label :price_high, class: 'mdl-textfield__label' %>
    <%= form.text_field :price_high, class: 'mdl-textfield__input' %>
  </div>

  <div class="mdl-textfield mdl-js-textfield" style="display: flex;">
    <%= form.label :event_date, class: 'mdl-textfield__label' %>
    <%= form.text_field :event_date, class: 'mdl-textfield__input' %>
  </div>

  <%= form.submit class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<% end %>

app/views/events/_list_tickets.html.erb
<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp"
       style="width: 100%; margin-top: 1rem;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Seat id seq</th>
      <th>Address</th>
      <th>Price</th>
      <th>Email address</th>
      <th>Phone</th>
    </tr>
  </thead>
  <tbody>
    <% tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.email_address %></td>
        <td><%= ticket.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_new_ticket.html.erb
<%= render 'tickets/form', ticket: ticket %>

app/views/events/index.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <h3>Events</h3>

    <a class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
       href="<%= new_event_path %>">
      Create new event
    </a>

    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp"
           style="width: 100%; margin-top: 1rem;">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">Artist</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td class="mdl-data-table__cell--non-numeric"><%= event.artist %></td>
            <td><%= link_to 'Show', event %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/events/new.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col">
    <h3>Create new event</h3>

    <%= render 'form', event: @event %>

    <br>
    <%= link_to 'Back', events_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="mdl-grid">
  <div class="mdl-cell--12-col">
    <p>
      <strong>Artist:</strong>
      <%= @event.artist %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @event.description %>
    </p>

    <p>
      <strong>Price low:</strong>
      <%= @event.price_low %>
    </p>

    <p>
      <strong>Price high:</strong>
      <%= @event.price_high %>
    </p>

    <p>
      <strong>Event date:</strong>
      <%= @event.event_date %>
    </p>

    <%= render 'new_ticket', ticket: Ticket.new(:event_id => @event.id) %>

    <%= render 'list_tickets', tickets: Ticket.where(event_id: @event.id) %>

    <br>
    <%= link_to 'Back', events_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
  </div>
</div>

app/views/home/index.html.erb
<div class="mdl-grid">
  <div class="mdl-cell--12-col">
    <h1 style="text-align: center">Hello</h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticketer</title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <%= link_to 'Ticketer', '/', class: 'mdl-layout-title', style: 'color: #fff; text-decoration: none'  %>

          <div class="mdl-layout-spacer"></div>

          <nav class="mdl-navigation">
            <%= link_to 'Events', events_path, class: 'mdl-navigation__link' %>

            <% if user_signed_in? %>
              <%= link_to 'Tickets', tickets_path, class: 'mdl-navigation__link' %>

              <%= link_to 'User profile', edit_user_registration_path, class: 'mdl-navigation__link' %>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'mdl-navigation__link' %>
            <% else %>
              <%= link_to 'Log in', new_user_session_path, class: 'mdl-navigation__link' %>
              <%= link_to 'Sign up', new_user_registration_path, class: 'mdl-navigation__link' %>
            <% end %>
          </nav>
        </div>
      </header>

      <main class="mdl-layout__content">
        <% if notice %>
          <div class="mdl-grid">
            <div class="mdl-cell">
              <div class="mdl-card mdl-shadow--2dp"
                   style="min-height: 0; background-color: rgba(0, 255, 0, .5)">
                <div class="mdl-card__title">
                  <%= notice %>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <% if alert %>
          <div class="mdl-grid">
            <div class="mdl-cell">
              <div class="mdl-card mdl-shadow--2dp"
                   style="min-height: 0; background-color: rgba(255, 0, 0, .5);">
                <div class="mdl-card__title">
                  <%= alert %>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <%= yield %>
      </main>

      <footer class="mdl-mini-footer">
        <div class="mdl-mini-footer__left-section">
          <div class="mdl-logo">Ticketer</div>
          <ul class="mdl-mini-footer__link-list">
            <li><%= link_to 'Events', events_path, class: 'mdl-navigation__link' %></li>
            <li><%= link_to 'Tickets', tickets_path, class: 'mdl-navigation__link' %></li>
          </ul>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation" class="mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title">
        <h6><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h6>
      </div>

      <div class="mdl-card__supporting-text">
        <ul>
          <% ticket.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="mdl-textfield mdl-js-textfield" style="display: flex;">
    <%= form.label :name, class: 'mdl-textfield__label' %>
    <%= form.text_field :name, class: 'mdl-textfield__input' %>
  </div>

  <div class="mdl-textfield mdl-js-textfield" style="display: flex;">
    <%= form.label :seat_id_seq, class: 'mdl-textfield__label' %>
    <%= form.text_field :seat_id_seq, class: 'mdl-textfield__input' %>
  </div>

  <div class="mdl-textfield mdl-js-textfield" style="display: flex;">
    <%= form.label :address, class: 'mdl-textfield__label' %>
    <%= form.text_area :address, class: 'mdl-textfield__input' %>
  </div>

  <div class="mdl-textfield mdl-js-textfield" style="display: flex;">
    <%= form.label :price, class: 'mdl-textfield__label' %>
    <%= form.text_field :price, class: 'mdl-textfield__input' %>
  </div>

  <div class="mdl-textfield mdl-js-textfield" style="display: flex;">
    <%= form.label :email_address, class: 'mdl-textfield__label' %>
    <%= form.text_field :email_address, class: 'mdl-textfield__input' %>
  </div>

  <div class="mdl-textfield mdl-js-textfield" style="display: flex;">
    <%= form.label :phone, class: 'mdl-textfield__label' %>
    <%= form.text_field :phone, class: 'mdl-textfield__input' %>
  </div>

  <%= form.hidden_field :event_id %>

  <%= form.submit class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<% end %>

app/views/tickets/edit.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <h1>Editing Ticket</h1>

    <%= render 'form', ticket: @ticket %>

    <br>
    <%= link_to 'Show', @ticket, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
    <%= link_to 'Back', tickets_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
  </div>
</div>

app/views/tickets/index.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <h3>Tickets</h3>

    <a class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
       href="<%= new_ticket_path %>">
      Create new ticket
    </a>

    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp"
           style="width: 100%; margin-top: 1rem;">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">Name</th>
          <th class="mdl-data-table__cell--non-numeric">Seat id seq</th>
          <th class="mdl-data-table__cell--non-numeric">Address</th>
          <th class="mdl-data-table__cell--non-numeric">Price</th>
          <th class="mdl-data-table__cell--non-numeric">Email address</th>
          <th class="mdl-data-table__cell--non-numeric">Phone</th>
          <th class="mdl-data-table__cell--non-numeric">Event id</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @tickets.each do |ticket| %>
          <tr>
            <td class="mdl-data-table__cell--non-numeric"><%= ticket.name %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= ticket.seat_id_seq %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= ticket.address %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= ticket.price %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= ticket.email_address %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= ticket.phone %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= ticket.event_id %></td>
            <td><%= link_to 'Show', ticket %></td>
            <% if ticket.user == current_user %>
              <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
              <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
              <td colspan="2"></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tickets/new.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col">
    <h3>Create new ticket</h3>

    <%= render 'form', ticket: @ticket %>

    <br>
    <%= link_to 'Back', tickets_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
  </div>
</div>

app/views/tickets/show.html.erb
<div class="mdl-grid">
  <div class="mdl-cell--12-col">
    <p>
      <strong>Name:</strong>
      <%= @ticket.name %>
    </p>

    <p>
      <strong>Seat id seq:</strong>
      <%= @ticket.seat_id_seq %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @ticket.address %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @ticket.price %>
    </p>

    <p>
      <strong>Email address:</strong>
      <%= @ticket.email_address %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @ticket.phone %>
    </p>

    <p>
      <strong>Event id:</strong>
      <%= @ticket.event_id %>
    </p>

    <% if @ticket.user == current_user %>
      <%= link_to 'Edit', edit_ticket_path(@ticket), class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
    <% end %>

    <%= link_to 'Back', tickets_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
  </div>
</div>